apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-deployment
spec:
  selector:
    matchLabels:
      app: java-api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - name: java-api
        image: java-api:latest
        ports:
        - containerPort: 2023
 
