server:
  port: 2024
  servlet:
    context-path: /app
    

security : 
  jwt : 
    secret-key : 6749577c76efb0cf8a90983cf0972f62082445c10be1250a4aeb09ac5c25b2f3
    expiration-time : 3600

kafka: 
  enable: false
  topic: example

spring:
  application:
    name: ecommerce
  profiles:
    active:
    - dev
  logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
 
 # config:
 #   import: optional:configserver:http://myconfigserver.com

---

spring:
  config:
    activate:
      on-profile : dev
    
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: ecompwd#24

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    
  integration:
    jdbc:
      initialize-schema: always
            
redis :
   database : 0
   host : localhost
   port : 16379
   password : mypass
   timeout : 60000
