server:
  port: 2024
  servlet:
    context-path: /app

security : 
  jwt : 
    secret-key : 6749577c76efb0cf8a90983cf0972f62082445c10be1250a4aeb09ac5c25b2f3
    expiration-time : 3600000

kafka: 
  enable: false
  topic: example

spring:
  logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO


---

spring:
  config:
    activate:
      on-profile : dev
    
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/app
    username: sa
    password: sa
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    
  integration:
    jdbc:
      initialize-schema: always
            
redis :
   database : 0
   host : localhost
   port : 16379
   password : mypass
   timeout : 60000
