server:
  port: 2020
  servlet:
    context-path: /app

jwt :
  secret : javainuse

spring:
logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO


---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/app
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa :
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect